server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_users
    username: root
    password: Azul061100.@/..-/./

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "plazoleta users microservice"
appVersion: "1.0.0"

jwt:
  secret: "qasshtipuuwnmcbwjcalibcieebnjolño29jne9djsallsdj-sdoo-ksks-o"
  expiration: 3600000

mall:
  service:
    url: http://localhost:8082